export const STUDENT_PATHS = {
  ROOT: '/student',
  ONBOARDING: '/student/onboarding',
  DASHBOARD: '/student/dashboard',
  STUDY_PLAN: '/student/study-plan',
  ASSIGNMENTS: '/student/assignments',
  ASSIGNMENT: (id) => `/student/assignments/${id}`,
  ASSIGNMENT_SUBMIT: (id) => `/student/assignments/${id}/submit`,
  ASSIGNMENT_FEEDBACK: (id) => `/student/assignments/${id}/feedback`,
  QUIZZES: '/student/quizzes',
  QUIZ_TAKE: (id) => `/student/quiz/${id}/take`,
  QUIZ_RESULTS: (id) => `/student/quiz/${id}/results`,
  EXAMS: '/student/exams',
  EXAM_TAKE: (id) => `/student/exam/${id}/take`,
  EXAM_PREPARE: (id) => `/student/exams/${id}/prepare`,
  EXAM_REFLECT: (id) => `/student/exams/${id}/reflect`,
  PIXGEN: '/student/pixgen',
  YOUTUBE_QUIZ: '/student/youtube-quiz',
  YOUTUBE_QUIZ_TAKE: (id) => `/student/youtube-quiz/${id}/take`,
  YOUTUBE_QUIZ_RESULTS: (id) => `/student/youtube-quiz/${id}/results`,
  TEMPLATES: '/student/templates',
  TEMPLATE: (id) => `/student/templates/${id}`,
  TUTORS: '/student/tutors',
  TUTOR_CHAT: (id) => `/student/tutors/${id}`,
  DOUBT_SOLVER: '/student/doubt-solver',
  DOUBT_SESSION: (id) => `/student/doubt-solver/${id}`,
  NOTES: '/student/notes',
  NOTE_NEW: '/student/notes/new',
  NOTE: (id) => `/student/notes/${id}`,
  SUBJECTS: '/student/subjects',
  SUBJECT_ROOM: (id) => `/student/subjects/${id}/room`,
  STUDY_TIME: '/student/study-time',
  GRADE_CALCULATOR: '/student/grade-calculator',
  TEACHERS: '/student/teachers',
  TEACHER: (id) => `/student/teachers/${id}`,
  DOUBTS: '/student/doubts',
  DOUBT: (id) => `/student/doubts/${id}`,
  TASKS: '/student/tasks',
  TASK_CREATE: '/student/tasks/create',
  TASK: (id) => `/student/tasks/${id}`,
  TASK_EDIT: (id) => `/student/tasks/${id}/edit`,
  CONTENT: '/student/content',
  CONTENT_SUBJECT: (id) => `/student/content/${id}`,
  CONTENT_WORKSHEET: (id) => `/student/content/worksheet/${id}`,
  TIMETABLE: '/student/timetable',
  PROGRESS: '/student/progress',
  PROGRESS_SUBJECT: (id) => `/student/progress/${id}`,
};

